Appointment
alexlead/doctor_appointment_app pull request #31
Opened 2024-03-19 15:03 UTC by armyan5

2024-03-19 15:13 UTC, Tetiana-Ilienko reviewed
you should write AppointmentInterface ( class Appointment implements  AppointmentInterface)

2024-03-19 15:13 UTC, alexlead requested changes
Please check columns' names 
doctor_id
patient_id
slot_id
visit_complete
And table title should be in lowcase

Проверь названия колонок, в базе данных они идут через знак подчеркивания. И название таблицы тоже с маленькой буквы (менее критично)

2024-03-19 15:16 UTC, Tetiana-Ilienko commented
И связи с другими таблицами нужно указать по примеру User. Смотри схему БД

2024-03-19 18:35 UTC, Tetiana-Ilienko commented on src/main/java/com/ait_31_2/doctor_appointment_app/domain/classes/Appointment.java
Вот тут указываешь имя колонки в таблице apointment, через которую идет связь
FetchType - тип загрузки либо совсем не указываешь, либо пишешь  FetchType.EAGER -
  @Id - нужна только у первой колонки (id)

 
    @ManyToOne(fetch = FetchType.EAGER)
    @Column(name = "patient_id",nullable = false)
    private User patientId;


  
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "doctor_id",nullable = false)
    private User doctorId;

2024-03-19 18:38 UTC, armyan5 commented on src/main/java/com/ait_31_2/doctor_appointment_app/domain/classes/Appointment.java
Tam esho est))tam vrode uje vsyo tak kak nujno,

2024-03-20 08:32 UTC, alexlead approved these changes

2024-03-20 08:33 UTC, Tetiana-Ilienko approved these changes

2024-03-20 08:35 UTC, zaplatynska-kira approved these changes

2024-03-20 10:26 UTC, merged